### ISSUE TITLE
Functional focus of library

### ISSUE THREAD

**Issue by elf55** [mdedonno1337/NIST#1]
It should be noted in the description of this library that the purpose is the processing of latent fingerprints and in particular the processing of marked minutiae.  This library is not for general parsing of NIST biometric files used to exchange fingerprints (or other biometrics) not related to a latent print workflow.

**Comment by mdedonno1337** [comment]
Well, yes and no.
The main kernel encoding and decoding the traditional files should be working with all files, but I agree with you that no functions are developed at the moment for other biometrics.

**Comment by elf55** [comment]
It is good work, but it would be good for you to explain your primary purpose in developing the package in the description.

**Comment by mdedonno1337** [comment]
The desc contains a "fingerprint oriented" mention, and the readme file a little note. Since the doc does not work at the moment anyway, will have to rework it anyway (when time will be available here).

The first aims was to facilitate my work with AFIS systems, and to allow my collegues to work with NIST fingerprint files (see the https://webnist.unil.ch/ webpage : you can drop a Type14 or Type04 and check the result)

Thanks for the feedback
